baseURL = "https://libptpmgmt.nwtime.org/"
title = "libptpmgmt Project"
enableRobotsTXT = true

[params.plugins]

# JS Plugins
  [[params.plugins.js]]
  link = "plugins/bootstrap-5.1.3/js/bootstrap.bundle.min.js"

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[languages]
[languages.en]
contentDir = "content/en"
title = "libptpmgmt Project"
languageName ="English"
weight = 1

##### needed for raw html in md files #####
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      style = "tango"

# Everything below this are Site Params

[params]
copyright = "Network Time Foundation"
logo2 = "images/logo.png"
github_repo = "https://github.com/erezgeva/libptpmgmt"
description = "GitHub repository"
images = ["/images/featured.webp"]

[[menu.main]]
    name = "Documentation"
    url = "/documentation/"
    weight = 10